name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-dev build-essential

    - name: Install Android SDK + Buildozer
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip sdk-tools.zip -d $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        mv $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest

        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;25.1.8937393"

        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

        pip install --upgrade pip
        pip install cython virtualenv buildozer

    - name: Initialize Buildozer (if needed)
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorldKivyApp
        path: bin/*.apk